[package]
name = "void"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.197", default-features = false, features = ["derive"] }
toml = "0.8.12"

[profile.release]
strip = "symbols"
