[package]
name = "protocol"
version = "0.1.0"
edition = "2021"

[dependencies]
base64 = "0.22.1"
serde = { version = "1.0", default-features = false, features = ["derive"] }
serde_json = "1"
gxhash = { version = "3", optional = true }
scc = { version = "2.1.1", features = ["serde"] }

[features]
# optionally use extremely fast gxhash hashing algo
# requires some CPU features, only works on x86_64 and aarch64
gxhash = ["dep:gxhash"]
