[package]
name = "protocol"
version = "0.1.0"
edition = "2021"

[dependencies]
base64 = "0.22.1"
serde = { version = "1.0", default-features = false, features = ["derive"] }
serde_json = "1"
scc = { version = "2.1", features = ["serde"] }
