[package]
name = "void"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.197", default-features = false, features = ["derive"] }
toml = "0.8.12"
env_logger = "0.11.3"
log = { version = "0.4.21", features = ["serde"] }
tokio = { version = "1", features = ["full"] }
tokio-stream = { version = "0.1", features = ["full"] }
tokio-native-tls = "0.3.1"
tokio-tungstenite = "0.21.0"
async-trait = "0.1.80"
futures-util = "0.3.30"
gxhash = { version = "3.2.0", optional = true }
rmp-serde = "1.3.0"

protocol = { path = "../protocol" }

[features]
# optionally use extremely fast gxhash hashing algo
# requires some CPU features, only works on x86_64 and aarch64
gxhash = ["dep:gxhash"]
